### ISSUE TITLE
[2021.11.19 회의록]

### ISSUE THREAD

**Issue by sally2596** [kotlin-with-prettiest/SE_AL#1]
# [2021.11.19 회의록]

작성자 : 전선영

### 📋 회의 안건

1. 팀프로젝트 이름 선정
    - SE:AL
   
2. 팀프로젝트 기획안 작성
    - <a href = "https://six-eye-dd4.notion.site/887f6ac8b157452793cf6caf091f872d">세부 기획안</a>
    - <a href = "https://docs.google.com/presentation/d/1KOGD70IwBIlUoYUVqpSaza3eQoh2eDeAr_qddGt5SlI/edit"> UI Wireframe </a>

### 📈 다음주 할 내용

|           Member         |                                         Do    |
|:-----------------------:|:---------------------------------------------------------------------------------------------:|
|  @sally2596 | 블랙보드/UIS 로그인 |
|  @byhhh2 | 블랙보드/UIS 로그인 |
| @hggew | 프로토타입 제작 & Project Initial Commit(상단탭) |
| @RightHennessy | 프로토타입 제작 &  Project Initial Commit(상단탭) |

### 🛠 개선 사항

- 회의 시작 시간 : 9시로 변경
- 회의록 작성 순서 : @sally2596 > @RightHennessy > @hggew > @byhhh2

### ➕ 추가 사항

- <a href="https://drive.google.com/drive/folders/1Z3CYxI7VuKi6yenU5HZdfjNfb0gYYABY?usp=sharing">공유 드라이브</a>

**Comment by hggew** [comment]
확인~

**Comment by RightHennessy** [comment]
확인 ~ ~

**Comment by byhhh2** [comment]
화긴 〰
