### ISSUE TITLE
[ 2021.12.02 회의록 ]

### ISSUE THREAD

**Issue by hggew** [kotlin-with-prettiest/SE_AL#10]
# [ 2021.12.02 회의록 ]

작성자 : 김현영

### 📋 회의 안건

1. 진행 상황
    - front-end : fragment 생성 미완
    - back-end : 로그인 세션 유지 미완 

### 📈 다음주 할 내용

|           Member         |                                         Do    |
|:-----------------------:|:---------------------------------------------------------------------------------------------:|
|  @sally2596 |  로그인 세션 유지, 뷰모델에 로그인 정보 저장, 앱 알림보내기 |
|  @byhhh2 | 로그인 세션 유지, 뷰모델에 로그인 정보 저장, 앱 알림보내기, <br> api 추가로 파악 |
| @hggew | 화면 fragment 생성, navigation 연결, recyclerview 변환 |
| @RightHennessy | 시험공부 |

### 🛠 개선 사항

- @RightHennessy 블랙보드 아이디로 과제,시험 정보 확인

### ➕ 추가 사항

-

**Comment by byhhh2** [comment]
화긴 ~~ 👍🏻

**Comment by sally2596** [comment]
췍췍

**Comment by RightHennessy** [comment]
확인확인 !~
