### ISSUE TITLE
[ 2021.12.23 회의록 ]

### ISSUE THREAD

**Issue by byhhh2** [kotlin-with-prettiest/SE_AL#11]
# [ 2021.12.23(목) 회의록]

작성자 : 변영화 😎✌️

### 📋 회의 안건

1. 네비게이션 문제 
    - navigate를 실행하면 에러 발생 
    - 상단탭에 대한 자료가 적음 
    - 하단탭으로 변경하면 에러 수정 가능할 듯 

#### 완료한 일 
|           구분         |                                         Done   |
|:-----------------------:|:---------------------------------------------------------------------------------------------:|
|  **Frontend** | navigation / fragment / recycler view 구축 |
|  **Backend** | 데이터베이스 모델 정의 / Room instance 생성 / notification build / work manager build  |

<br />

### 📈 다음주 할 내용

|           Member         |                                         Do    |
|:-----------------------:|:---------------------------------------------------------------------------------------------:|
|  @sally2596 | work manager를 통해서 notification 완성하기 |
|  @byhhh2 | Room으로 데이터베이스 모델링 완성하기 |
| @hggew | 상단탭을 하단탭으로 변경해보면서 네비게이션 완성하기 |
| @RightHennessy | 상단탭을 하단탭으로 변경해보면서 네비게이션 완성하기 |

<br />

### 🛠 개선 사항

- 없음

<br />

### ➕ 추가 사항

- 연말 약속으로 인해 회의 `29일 수요일 오후 10시`로 변경 
- 다들 아자아자 화이팅 ~! 😍

**Comment by RightHennessy** [comment]
확인했습니다 ~ ^_^

**Comment by sally2596** [comment]
마이크 췍 원투 원투

**Comment by hggew** [comment]
확인~~
