### ISSUE TITLE
[ 2021.12.29 회의록 ] 

### ISSUE THREAD

**Issue by sally2596** [kotlin-with-prettiest/SE_AL#12]
# [ 2021.12.29 회의록 ]

작성자 : 전선영

### 📋 회의 안건
1. 완료한 일 및 다음주까지 해야할 일

#### 완료한 일 
|           구분         |                                         Done   |
|:-----------------------:|:---------------------------------------------------------------------------------------------:|
|  **Frontend** | 네이게이션 하단바 전환 완료 |
|  **Backend** | 데이터베이스 구축/ 1분마다 데이터 갱신 및 앱 알림  |

<br />

### 📈 다음주 할 내용

|           Member         |                                         Do    |
|:-----------------------:|:---------------------------------------------------------------------------------------------:|
|  @sally2596 | 데이터베이스와 workmanager연결 및 알림, 알림용 데이터베이스 구축, 강의 시간 받아오기 |
|  @byhhh2 | 데이터베이스와 workmanager연결 및 알림, 알림용 데이터베이스 구축, 강의 시간 받아오기 |
| @hggew | 화면 전환 해결하기, 리사이클러뷰에 데이터베이스 연결하기 |
| @RightHennessy | 화면 전환 해결하기, 리사이클러뷰에 데이터베이스 연결하기 |

### 🛠 개선 사항

- 없음

### ➕ 추가 사항

- 원래 회의 시간인 `목요일 오후 9시`로 돌아오기

**Comment by RightHennessy** [comment]
확인했습니다 ~ >_<

**Comment by hggew** [comment]
확인~~

**Comment by byhhh2** [comment]
확인 ~! 😁
