### ISSUE TITLE
[ 2022.01.06 회의록 ]

### ISSUE THREAD

**Issue by RightHennessy** [kotlin-with-prettiest/SE_AL#13]
# [ 2022.01.06 회의록]

작성자 : 최예린💙

### 📋 회의 안건

1.  완료한일 및 다음주까지 할 일

#### 완료한 일 
|           구분         |                                         Done   |
|:-----------------------:|:---------------------------------------------------------------------------------------------:|
|  **Frontend** | 화면전환 완료, 리사이클러뷰 생성 |
|  **Backend** | 데이터베이스 구축  |

<br />

### 📈 다음주 할 내용

|           Member         |                                         Do    |
|:-----------------------:|:---------------------------------------------------------------------------------------------:|
|  @sally2596 | 데이터베이스와 workmanager연결 및 알림 |
|  @byhhh2 | 데이터베이스 접근을 위한 sql query문 만들기  |
| @hggew | 로그인 화면, 버튼 연결, 리사이클러뷰 해결 |
| @RightHennessy | 로그인 화면, 버튼 연결, 리사이클러뷰 해결 |

### 🛠 개선 사항

- 개선 사항은 없습니다. 

### ➕ 추가 사항

- 프런트와 백 병합을 위해 `목요일 오후 8시`에 회의 시작합니다 ~
- 새해 첫 회의였네요.. 다들 새해 복 많이 받으십쇼 😊

**Comment by byhhh2** [comment]
새복많 😘~~

**Comment by sally2596** [comment]
HAPPY... NEW YEAR....

**Comment by hggew** [comment]
확인확인
