### ISSUE TITLE
[ 2022.01.13 회의록 ]

### ISSUE THREAD

**Issue by hggew** [kotlin-with-prettiest/SE_AL#16]
# [ 2022.01.13 회의록 ]

작성자 : 김현영

### 📋 회의 안건

1. 코드 합치기 & 코드 설명
2. 다음주까지 할 일

### 📈 다음주 할 내용

|           Member         |                                         Do    |
|:-----------------------:|:---------------------------------------------------------------------------------------------:|
|  @sally2596 | worker로 처음에 DB 받아오기(login 첫번째 실행), <br>worker로 DB 업데이트, calendar DB에서 시간 비교해서 알림 보내기 |
|  @byhhh2 | 로그인 정보 DB 저장, 코드 정리  |
| @hggew | 로그인 정보 Main 전달, 로그인 실패 시 알림, <br>Main 화면에서 키보드 없애기, 로그아웃 -> 앱초기화 |
| @RightHennessy | DB와 리사이클러뷰 연결 |

### 🛠 개선 사항

- 없음

### ➕ 추가 사항

- 원래 회의 시간인 목요일 오후 9시로 돌아오기
- <a href = "https://utopian-galley-07b.notion.site/9356d85e615c43259d2f3c2a751ff1ea">Front에서 사용할 쿼리  </a>
- cmd 꿀팁 : 주소창에 cmd 입력하기
- @sally2596 마무리 못하면 3만원 💸💸

<br>

**Comment by RightHennessy** [comment]
확인확인 ~

**Comment by byhhh2** [comment]
확인 ~~ 😙 꿀팁 좋네요..

**Comment by sally2596** [comment]
체키라웃
