### ISSUE TITLE
[ 2021.11.25 회의록]

### ISSUE THREAD

**Issue by RightHennessy** [kotlin-with-prettiest/SE_AL#4]
# [ 2021.11.25 회의록]

작성자 : 최예린💙

### 📋 회의 안건

1. 진행 상황

    - 프로토타입 제작 : <a href = "https://www.figma.com/proto/Rbo3Istm8HFjXlb3HFT6BW/SE%3AAL_proto?page-id=0%3A1&node-id=2%3A28&viewport=241%2C48%2C0.24&scaling=scale-down&starting-point-node-id=2%3A28&show-proto-sidebar=1">UI Prototype</a>
    - Project Initial commit까지 완료
    -  UIS 로그인까지 완성 ❕ (정말 수고했다💕)
    
2. 변수명 이슈로 공유
    - <a href = "https://github.com/kotlin-with-prettiest/SE_AL/issues/3">변수명과 설명</a>
   
3. 백엔드 계획 
    
    - 로그인 세션 유지
    -  json 데이터 정제 -> 현재 듣고 있는 강의 목록 띄우기
    - 강의 id를 통해서 강의 안의 내용 가져오기 (과제, 시험 등)

### 📈 다음주 할 내용

|           Member         |                                         Do    |
|:-----------------------:|:---------------------------------------------------------------------------------------------:|
|  @sally2596 | 로그인 세션 유지,  json 데이터 |
|  @byhhh2 | 로그인 세션 유지,  json 데이터 |
| @hggew | 화면 fragment 생성, 버튼으로 화면 이동 |
| @RightHennessy | 화면 fragment 생성, 버튼으로 화면 이동 |

### 🛠 개선 사항

-  프론트엔드는 branch 생성해서 작업해 주세요.

### ➕ 추가 사항

- 풀리퀘스트 템플릿이 생성되었습니다. 확인해주세요.
- 코틀린 포맷터  <a href = "https://blog.benelog.net/ktlint.html">2. intellij 설정 </a>참고해주세요.

**Comment by hggew** [comment]
확인했슴둥

**Comment by byhhh2** [comment]
확인 🥰 숙오했숨둥..

**Comment by sally2596** [comment]
CHECK
